/** Canonical route name constants. Use instead of raw strings in router.push(). */
export const ROUTE_NAMES = {
  DASHBOARD: 'dashboard',
  HISTORY: 'history',
  ANALYTICS: 'analytics',
  ACCOUNTS: 'accounts',
  NEW_ACCOUNT: 'new-account',
  ACCOUNT_DETAIL: 'account-detail',
  NEW_TRANSACTION: 'new-transaction',
  DEBTS_LIST: 'debts-list',
  DEBT_DETAIL: 'debt-detail',
  PROFILE: 'profile',
  CHANGELOG: 'changelog',
  SETTINGS_CURRENCY: 'settings-currency',
  SETTINGS_LANGUAGE: 'settings-language',
  SETTINGS_IMPORT: 'settings-import',
  SETTINGS_CATEGORIES: 'settings-categories',
  PEOPLE_LIST: 'people-list',
  SETTINGS_QUICK_ACTIONS: 'settings-quick-actions',
  SETTINGS_COLOR: 'settings-color',
  SCAN_RECEIPT: 'scan-receipt',
  SHARED_RECEIPT: 'shared-receipt',
  IMPORT_INBOX: 'import-inbox',
  IMPORT_CONFIRM: 'import-confirm',
  DASHBOARD_SETTINGS: 'dashboard-settings',
  SUBSCRIPTIONS_LIST: 'subscriptions-list',
  SUBSCRIPTION_DETAIL: 'subscription-detail',
  NEW_SUBSCRIPTION: 'new-subscription',
  WELCOME: 'welcome',
  LOGIN: 'login',
  AUTH_CALLBACK: 'auth-callback',
  FIRST_ACCOUNT: 'first-account',
} as const;
