// TODO: consider lazy-loading icons to reduce main chunk size.
import type { Component } from 'vue';
import {
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Baby,
  Scale,
  Camera,
  Images,
  Crop,
  Type,
  ScanLine,
  BadgeAlert,
  BadgeCheck,
  Banknote,
  Bell,
  Bot,
  Briefcase,
  Bug,
  CalendarCheck,
  CalendarDays,
  Car,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Cigarette,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  Cloud,
  Play,
  Clapperboard,
  Coffee,
  Copy,
  CreditCard,
  Cross,
  Crown,
  Diamond,
  Download,
  Droplets,
  Dumbbell,
  Ellipsis,
  Eye,
  NotebookPen,
  Tag,
  EyeOff,
  Flag,
  Frown,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  GripVertical,
  HandHeart,
  Handshake,
  Heart,
  HeartPulse,
  History,
  Home,
  House,
  Inbox,
  Info,
  Landmark,
  Languages,
  Laptop,
  Lock,
  Laugh,
  LayoutGrid,
  Link2,
  List,
  ListOrdered,
  ListFilter,
  ListVideo,
  LogOut,
  Mail,
  MailCheck,
  Meh,
  Minus,
  Moon,
  Music,
  Music2,
  Palette,
  PartyPopper,
  PawPrint,
  Pencil,
  PieChart,
  PiggyBank,
  Plane,
  Plus,
  Receipt,
  ReceiptText,
  RefreshCw,
  Repeat,
  Reply,
  ReplyAll,
  Rows2,
  Rows3,
  Scissors,
  Search,
  Send,
  Settings,
  Share2,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sparkles,
  SprayCan,
  Star,
  Sun,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Tv,
  Undo2,
  User,
  UserPlus,
  UsersRound,
  Users,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  X,
  Zap,
} from 'lucide-vue-next';

export const iconMap: Record<string, Component> = {
  account_balance: Landmark,
  balance: Scale,
  photo_camera: Camera,
  photo_library: Images,
  crop_free: Crop,
  text_fields: Type,
  document_scanner: ScanLine,
  error_outline: CircleAlert,
  receipt: Receipt,
  person_add: UserPlus,
  group_add: UsersRound,
  expand_less: ChevronUp,
  account_balance_wallet: Wallet,
  add: Plus,
  apps: LayoutGrid,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  auto_awesome: Sparkles,
  bolt: Zap,
  bug_report: Bug,
  build: Wrench,
  call_split: Scissors,
  calendar_month: CalendarDays,
  calendar_today: CalendarCheck,
  cardiology: HeartPulse,
  category: LayoutGrid,
  celebration: PartyPopper,
  check: Check,
  check_circle: CircleCheck,
  checkroom: Shirt,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  child_care: Baby,
  cleaning_services: SprayCan,
  close: X,
  cottage: House,
  content_copy: Copy,
  credit_card: CreditCard,
  credit_score: BadgeCheck,
  currency_exchange: ArrowLeftRight,
  dark_mode: Moon,
  delete: Trash2,
  density_small: Rows3,
  done_all: CheckCheck,
  diamond: Diamond,
  download: Download,
  directions_car: Car,
  drag_indicator: GripVertical,
  edit: Pencil,
  edit_note: NotebookPen,
  electric_bolt: Zap,
  error: CircleAlert,
  expand_more: ChevronDown,
  family_restroom: Users,
  favorite: Heart,
  filter_list: ListFilter,
  fitness_center: Dumbbell,
  flag: Flag,
  flight: Plane,
  group: UsersRound,
  handshake: Handshake,
  history: History,
  home: Home,
  inbox: Inbox,
  info: Info,
  language: Languages,
  laptop_mac: Laptop,
  light_mode: Sun,
  link: Link2,
  list: List,
  format_list_numbered: ListOrdered,
  local_bar: Wine,
  local_cafe: Coffee,
  local_gas_station: Fuel,
  local_shipping: Truck,
  logout: LogOut,
  lock: Lock,
  mail: Mail,
  mark_email_read: MailCheck,
  medical_services: Cross,
  monetization_on: CircleDollarSign,
  more_horiz: Ellipsis,
  movie: Clapperboard,
  music_note: Music,
  new_releases: BadgeAlert,
  palette: Palette,
  notifications: Bell,
  payments: Banknote,
  person: User,
  pets: PawPrint,
  phone_android: Smartphone,
  phone_iphone: Smartphone,
  pie_chart: PieChart,
  play_arrow: Play,
  receipt_long: ReceiptText,
  redeem: Gift,
  refresh: RefreshCw,
  remove: Minus,
  repeat: Repeat,
  reply: Reply,
  reply_all: ReplyAll,
  restaurant: UtensilsCrossed,
  savings: PiggyBank,
  school: GraduationCap,
  search: Search,
  sell: Tag,
  settings: Settings,
  share: Share2,
  sentiment_neutral: Meh,
  sentiment_satisfied: Smile,
  sentiment_very_dissatisfied: Frown,
  sentiment_very_satisfied: Laugh,
  shopping_basket: ShoppingBasket,
  shopping_cart: ShoppingCart,
  smoking_rooms: Cigarette,
  sports_esports: Gamepad2,
  star: Star,
  subscriptions: ListVideo,
  swap_horiz: ArrowLeftRight,
  swap_vert: ArrowUpDown,
  timer: Timer,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  tv: Tv,
  undo: Undo2,
  view_agenda: Rows2,
  visibility: Eye,
  visibility_off: EyeOff,
  volunteer_activism: HandHeart,
  warning: TriangleAlert,
  water_drop: Droplets,
  workspace_premium: Crown,
  wifi: Wifi,
  work: Briefcase,

  // Service subscription presets
  netflix: Clapperboard,
  spotify: Music,
  youtube: Play,
  apple_music: Music2,
  icloud: Cloud,
  telegram: Send,
  yandex_plus: Star,
  chatgpt: Bot,
  cloud: Cloud,
};
