import type { Component } from 'vue';
import {
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Baby,
  BadgeAlert,
  BadgeCheck,
  Banknote,
  Bell,
  Briefcase,
  Bug,
  CalendarCheck,
  CalendarDays,
  Car,
  Check,
  ChevronDown,
  ChevronRight,
  Cigarette,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CirclePlay,
  Play,
  CircleArrowDown,
  Clapperboard,
  Coffee,
  CreditCard,
  Cross,
  Diamond,
  Droplets,
  Dumbbell,
  Ellipsis,
  Eye,
  EyeOff,
  Flag,
  Frown,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  GripVertical,
  HandHeart,
  Heart,
  HeartPulse,
  History,
  Home,
  House,
  Info,
  Landmark,
  Laptop,
  Lock,
  Laugh,
  LayoutGrid,
  List,
  ListVideo,
  LogOut,
  Mail,
  MailCheck,
  Meh,
  Minus,
  Moon,
  Music,
  PartyPopper,
  PawPrint,
  Pencil,
  PieChart,
  PiggyBank,
  Plane,
  Plus,
  Receipt,
  Reply,
  ReplyAll,
  Search,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sparkles,
  SprayCan,
  Star,
  Sun,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Tv,
  User,
  UsersRound,
  Users,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  X,
  Zap,
} from 'lucide-vue-next';

export const iconMap: Record<string, Component> = {
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  add: Plus,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_outward: ArrowUpRight,
  auto_awesome: Sparkles,
  bolt: Zap,
  bug_report: Bug,
  build: Wrench,
  call_received: CircleArrowDown,
  calendar_month: CalendarDays,
  calendar_today: CalendarCheck,
  cardiology: HeartPulse,
  category: LayoutGrid,
  celebration: PartyPopper,
  check: Check,
  check_circle: CircleCheck,
  checkroom: Shirt,
  chevron_right: ChevronRight,
  child_care: Baby,
  cleaning_services: SprayCan,
  close: X,
  cottage: House,
  credit_card: CreditCard,
  credit_score: BadgeCheck,
  currency_exchange: ArrowLeftRight,
  dark_mode: Moon,
  delete: Trash2,
  diamond: Diamond,
  directions_car: Car,
  drag_indicator: GripVertical,
  edit: Pencil,
  electric_bolt: Zap,
  error: CircleAlert,
  expand_more: ChevronDown,
  family_restroom: Users,
  favorite: Heart,
  fitness_center: Dumbbell,
  flag: Flag,
  flight: Plane,
  group: UsersRound,
  history: History,
  home: Home,
  info: Info,
  laptop_mac: Laptop,
  light_mode: Sun,
  list: List,
  local_bar: Wine,
  local_cafe: Coffee,
  local_gas_station: Fuel,
  local_shipping: Truck,
  logout: LogOut,
  lock: Lock,
  mail: Mail,
  mark_email_read: MailCheck,
  medical_services: Cross,
  monetization_on: CircleDollarSign,
  more_horiz: Ellipsis,
  movie: Clapperboard,
  music_note: Music,
  new_releases: BadgeAlert,
  notifications: Bell,
  payments: Banknote,
  person: User,
  pets: PawPrint,
  phone_android: Smartphone,
  phone_iphone: Smartphone,
  pie_chart: PieChart,
  play_arrow: Play,
  play_circle: CirclePlay,
  receipt_long: Receipt,
  redeem: Gift,
  remove: Minus,
  reply: Reply,
  reply_all: ReplyAll,
  restaurant: UtensilsCrossed,
  savings: PiggyBank,
  school: GraduationCap,
  search: Search,
  sentiment_neutral: Meh,
  sentiment_satisfied: Smile,
  sentiment_very_dissatisfied: Frown,
  sentiment_very_satisfied: Laugh,
  shopping_basket: ShoppingBasket,
  shopping_cart: ShoppingCart,
  smoking_rooms: Cigarette,
  sports_esports: Gamepad2,
  star: Star,
  subscriptions: ListVideo,
  swap_horiz: ArrowLeftRight,
  timer: Timer,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  tv: Tv,
  visibility: Eye,
  visibility_off: EyeOff,
  volunteer_activism: HandHeart,
  warning: TriangleAlert,
  water_drop: Droplets,
  wifi: Wifi,
  work: Briefcase,
};
