export { ENTITY_COLORS as CATEGORY_COLORS } from '@/shared/config/colors';

export const CATEGORY_ICONS = [
  // Common expense
  'shopping_basket',
  'restaurant',
  'directions_car',
  'local_gas_station',
  'home',
  'cottage',
  'fitness_center',
  'school',
  'medical_services',
  'cardiology',
  'flight',
  'movie',
  'sports_esports',
  'pets',
  'child_care',
  'family_restroom',
  'checkroom',
  'phone_android',
  'wifi',
  'local_cafe',
  'local_bar',
  'smoking_rooms',
  'cleaning_services',
  'volunteer_activism',
  // Common income
  'payments',
  'work',
  'trending_up',
  'savings',
  'redeem',
  'credit_score',
  'account_balance',
  'monetization_on',
  // Generic
  'receipt_long',
  'category',
  'more_horiz',
  'star',
  'favorite',
  'shopping_cart',
  'local_shipping',
  'build',
  'credit_card',
  'bolt',
  'diamond',
  'flag',
  'music_note',
  'palette',
  'water_drop',
  'celebration',
];
